### ISSUE TITLE
worser test result on nyu dataset

### ISSUE THREAD

**Issue by hurricane2018** [MehmetAygun/fusenet-pytorch#10]
First, I use the default code to train the model on nyu dataset. 
Second, I test the nyu dataset using the default code. 
However, I get a very bad result as shown in the following figure. Could you give me some suggestion?

![image](https://user-images.githubusercontent.com/36166137/56275228-dd442300-6132-11e9-8308-315ae746bc4b.png)

Best,

**Comment by hurricane2018** [comment]
@MehmetAygun @hazirbas  Can you help me ?

**Comment by MehmetAygun** [comment]
Hey @hurricane2018, it seems you used the last saved checkpoint for testing, which can be not a very good model. Can you look your log, and find which checkpoint has lower loss, and test using that model.

**Comment by Alice-kenan** [comment]
Hi,  Can you provide more information for training the model on caffe?about how to get the rgb-d  lmdb data.
Looking forward to your reply!

**Comment by MehmetAygun** [comment]
@Alice-kenan for caffe implementation please refer to : https://github.com/tum-vision/fusenet

**Comment by Alice-kenan** [comment]
@MehmetAygun OK, thanks for your reply!
