### ISSUE TITLE
How to get images of segmentation map (with the 40 classes) 

### ISSUE THREAD

**Issue by Scienceseb** [MehmetAygun/fusenet-pytorch#13]
When saving the labels in png everything is black, its working for the depth and rgb but not the labels (segmentation map)...need your help for that.  I think Im messing up something maybe the scene ID and the class I dont know. I just want to obtain the segmentation map with the reduced number of class like in that repo https://github.com/zanilzanzan/FuseNet_PyTorch

**Comment by MehmetAygun** [comment]
Please look into https://github.com/MehmetAygun/fusenet-pytorch/issues/6#issuecomment-549083777

**Comment by Scienceseb** [comment]
but you do segmentation without segmentation map...i don’t really understand how you do your segmentation ....
