### ISSUE TITLE
assertion error when running with visdom server

### ISSUE THREAD

**Issue by sreshu** [MehmetAygun/fusenet-pytorch#16]
![ree2](https://user-images.githubusercontent.com/18489140/90062926-1b8d2a80-dd06-11ea-97bc-225c7f710634.png)

**Comment by hazirbas** [comment]
This could be a reason of using the latest version of visdom. Are you using [visdom==0.1.8.5](https://github.com/MehmetAygun/fusenet-pytorch/blob/master/requirements.txt)?

**Comment by sreshu** [comment]
@hazirbas do i need latest version than 0.1.8.5?

**Comment by hazirbas** [comment]
It depends how you install the packages, do you install latest version of them or you installed from the requirements.txt ? And it could be that you are sending non-square images while your visdom setting expects a square image?

**Comment by sreshu** [comment]
I installed from requirement.txt and data set is nyu only

**Comment by hazirbas** [comment]
I think error comes from [here](https://github.com/MehmetAygun/fusenet-pytorch/blob/master/util/visualizer.py#L183). You can easily debug and see what you are sending to visdom, otherwise you can always train without visdom.
