### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by xumingzhang-2018** [MehmetAygun/fusenet-pytorch#2]
Hello！
When I ran your code, I encountered the following errors：

FileNotFoundError: [Errno 2] No such file or directory: 'datasets/sunrgbd/images-224/7075.png'

Can you tell me how to get “datasets/sunrgbd/images-224/7075.png'”

Thanks!

**Comment by hazirbas** [comment]
You should download sunrgbd dataset and save images, depth maps and labels in .png format, by scaling the images to 224 (bilinear for images and nearest interpolation for the others).

I suggest you to start with NYUv2 dataset as we have the required scripts for it under /datasets.
