### ISSUE TITLE
How to evaluate each class of iou

### ISSUE THREAD

**Issue by caibi-xuexi** [MehmetAygun/fusenet-pytorch#22]
I have learned your fusenet from github,it introduced well,but I meet some problem when I reproduce this code:How to evaluate each class of iou like your following table.I can't find this test code.Or maybe I can't recognize that code if you have given it on the github.So would you please give me some guidance or that test code to relize the function that evaluate each class of iou,mean accuracy on scannetv2?My email is 1198317677@qq.com.Thank you very much.

scannetv2-test	avg iou	bathtub	bed	bookshelf	cabinet	chair	counter	curtain	desk	door	floor	other furniture	picture	refrigerator	shower curtain	sink	sofa	table	toilet	wall	window
no-cls_weighted	52.1	59.1	68.2	22.0	48.8	27.9	34.4	61.0	46.1	47.5	91.0	29.3	44.7	51.2	39.7	61.8	56.7	45.2	73.4	78.2	56.6
cls_weighted	53.5	57.0	68.1	18.2	51.2	29.0	43.1	65.9	50.4	49.5	90.3	30.8	42.8	52.3	36.5	67.6	62.1	47.0	76.2	77.9	54.1

**Comment by hazirbas** [comment]
Hey,
Please check out Scannet Benchmark Challenge:
http://kaldir.vc.in.tum.de/scannet_benchmark

**Comment by caibi-xuexi** [comment]
wow，you are the first author of FuseNet paper,I admire you and I read that paper many times.It's my pleasure to receive your reply.
But your little fanboy is so stupid.I have checked out that website(http://kaldir.vc.in.tum.de/scannet_benchmark),there are many benchmark results of different method and some introductions about this dataset.I also don't kown how to get IOU of every category.
I have trained this model on github,&nbsp; " python train.py --dataroot datasets/scannet/tasks/scannet_frames_25k --dataset scannetv2 --name scannetv2" ,this order can generate a document about IOU of full resolution
and "python test.py --dataroot datasets/scannet/tasks/scannet_frames_test --dataset scannetv2 --name scannetv2 --epoch 380 --phase test" can just get segmentation image.
So I still don't kown how to calculate each class of iou.
Thanks again!
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MehmetAygun/fusenet-pytorch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月16日(星期一) 中午1:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MehmetAygun/fusenet-pytorch] How to evaluate each class of iou (#22)





 
Hey,
 Please check out Scannet Benchmark Challenge:
 http://kaldir.vc.in.tum.de/scannet_benchmark
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hazirbas** [comment]
hey, you should upload your results to their servers, then they can compute it for you.
