### ISSUE TITLE
RGB fine tuning

### ISSUE THREAD

**Issue by andreaceruti** [MehmetAygun/fusenet-pytorch#26]
Hi! Do you think that is possible to fine tune the weights with only using an RGB dataset? I have an RGB-D dataset and a RGB dataset of grape bunches and I would like to train the net with both types of data.

Sorry if I am a bit redundant since I have opened the same issue in "Fusenet_Pytorch" repo

**Comment by hazirbas** [comment]
You could feed zero-filled depth maps =D for RGB data.

**Comment by andreaceruti** [comment]
Ok thank you @hazirbas  I will try
