### ISSUE TITLE
How i can train fusenet in my custom dataset??

### ISSUE THREAD

**Issue by achrefjarray** [MehmetAygun/fusenet-pytorch#29]
How i can train fusenet in my custom dataset

**Comment by hazirbas** [comment]
Hi,
you can implement your data reader, similar to
https://github.com/MehmetAygun/fusenet-pytorch/blob/master/data/sunrgbd_dataset.py

**Comment by achrefjarray** [comment]
If you can help me sir ?? I want do binair  classification
