### ISSUE TITLE
Cannot open nyuv2_40class_mapping.mat file?

### ISSUE THREAD

**Issue by gaoxiaoning** [MehmetAygun/fusenet-pytorch#6]
the error is  File "/usr/local/lib/python3.5/dist-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 105, 116?
it seem that the mat file is cantain some illegal string or char,can you supply the mat with txt or other format。thank you very much

**Comment by gaoxiaoning** [comment]
this line :mapping =  sio.loadmat("nyuv2/nyuv2_40class_mapping.mat")["mapping"][0]

**Comment by MehmetAygun** [comment]
Hi can you download file using a web browser, it seems that wget cannot properly download the file.

**Comment by gaoxiaoning** [comment]
Yes，I can download it,but use loadmat does not work ,I use some other mapping file to load(https://github.com/ankurhanda/nyuv2-meta-data),it works,thank you very much

**Comment by hurricane2018** [comment]
Same Problem. How did you solve it? @gaoxiaoning  @MehmetAygun

**Comment by MehmetAygun** [comment]
@hurricane2018 have you downloaded from this adres : https://github.com/tum-vision/fusenet/blob/master/fusenet/data/nyuv2_40class_mapping.mat

Because when you use wget it cannot download properly.

Also maybe it can be related to python version. I had no problem when I used python3.

**Comment by hurricane2018** [comment]
@MehmetAygun  Solved it. Thank you very much!

**Comment by Scienceseb** [comment]
Not working for me go the same error:
Traceback (most recent call last):
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 74, in <module>
    main()
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 71, in main
    create_dataset("nyu2")
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 66, in create_dataset
    create_nyu2()
  File "/media/seb/SSD2/fusenet-pytorch/datasets/create_training_set.py", line 16, in create_nyu2
    mapping =  sio.loadmat("nyuv2/nyuv2_40class_mapping.mat")["mapping"][0]
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 63, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/home/seb/anaconda3/envs/radar/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 105, 116


I use Python 3.7

**Comment by MehmetAygun** [comment]
@Scienceseb did you try above suggestions ? Downloading from web browser or from the link gaoxiaoning provided ?

**Comment by Scienceseb** [comment]
Thanks you your link work ! Why that error ???

**Comment by Scienceseb** [comment]
But when saving the labels in png everything is black, its working for the depth and rgb but not the labels (segmentation map)...need your help for that

**Comment by MehmetAygun** [comment]
Since labels between 0-number of class when it converted to rgb image, it represent a nearly a black image. 

You can look the [code](https://github.com/MehmetAygun/fusenet-pytorch/blob/1a316437899a0c402b0986e126b719da4fadd891/util/visualizer.py#L19) for how to get a meaningful picture of labels.

**Comment by Scienceseb** [comment]
so you are saying that pixel value are between 0-40 on 255, ok but my image is pitch black no variation...

**Comment by Scienceseb** [comment]
And just to know you select 40 classes to do the segmentation and the other classes are all zero or no ?

**Comment by sreshu** [comment]
facing the same error for without 40 classes' one .mat file

**Comment by hazirbas** [comment]
Hi, @Scienceseb, that file is a mapping from X class to 40 classes. So for a pixel you can map to new class as:
`newI[x][y] = map40[I[x][y]]`. And as Mehmet pointed out, you can colorize the image using a color palette.
