### ISSUE TITLE
ModuleNotFoundError: No module named 'models.cycle_gan_model'

### ISSUE THREAD

**Issue by somebodyus** [MehmetAygun/fusenet-pytorch#7]
```
from .cycle_gan_model import CycleGANModel  ModuleNotFoundError: 
No module named 'models.cycle_gan_model'
```

I come across this error. It seems that there should be `cycle_gan_model.py` file in the folder that contains `test_model.py`, but there is no such file. Could anyone help me?

**Comment by MehmetAygun** [comment]
which script are you running  ?

**Comment by hazirbas** [comment]
Hi, you should use test.py.

/models/test_model.py is not related to our project and we will remove it as it comes from [pix2pix](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix).

**Comment by somebodyus** [comment]
Then, another error appears.

`ModuleNotFoundError: No module named 'models.test_model'`

**Comment by maxjaritz** [comment]
The option `--model fusenet` has to be used or else the following error occurs:
`ModuleNotFoundError: No module named 'models.test_model'`

**Comment by hazirbas** [comment]
hey,
what dont you fix it in train test options file and submit a pull request?

Thanks!

**Comment by maxjaritz** [comment]
done
